// frontend/src/pages/Home.tsx
import React from "react";
import { Link } from "react-router-dom";
import {
  Box,
  BoxProps,
  Flex,
  Grid,
  Heading,
  Image,
  Text,
} from "@chakra-ui/react";

const Card: React.FC<BoxProps> = (props) => (
  <Box
    sx={{
      p: 2,
      height: "100%",
      color: "green.500",
      borderColor: "green.500",
      borderRadius: 5,
      borderWidth: 2,
      transition: "all ease-in 0.3s",
    }}
    _hover={{
      color: "white",
      backgroundColor: "green.500",
    }}
    {...props}
  />
);
const Home: React.FC = () => {
  return (
    <Flex direction="column">
      <Box>
        <Link to="/">
          <Image
            src="/src/assets/images/logo.png"
            sx={{ maxHeight: "10vh", margin: "auto" }}
          />
        </Link>
      </Box>
      <Box p={5}>
        <Text>Ver.2.0-dev</Text>
        <Text>
          最新のバージョンは
          <a
            href="https://github.com/newt-20st/score-watcher/releases"
            target="_blank"
          >
            こちらのリポジトリ
          </a>
          から確認してください。
        </Text>
      </Box>
      <Box p={5}>
        <Heading fontSize="2xl">形式を選択</Heading>
        <Grid
          templateColumns="repeat(auto-fit, minmax(250px, 1fr))"
          gap={5}
          py={5}
        >
          <Link to="/json">
            <Card>
              <Heading fontSize="xl">設定ファイルから読み込む</Heading>
              <Box>
                過去に設定した際に出力したファイルから形式データを読み込みます。
              </Box>
            </Card>
          </Link>
          <Link to="/config/count">
            <Card>
              <Heading fontSize="xl">スコア計算</Heading>
              <Box>単純なスコアを計算します。</Box>
            </Card>
          </Link>
          <Link to="/config/nomx">
            <Card>
              <Heading fontSize="xl">N o M x</Heading>
              <Box>N回正解で勝ち抜け、M回誤答で失格の形式です。</Box>
            </Card>
          </Link>
          <Link to="/config/nbyn">
            <Card>
              <Heading fontSize="xl">N by N</Heading>
              <Box>
                正答数と誤答数2つの変数を持ち、それぞれの初期値は0とNです。2つの変数の積がN
                ** 2に達したら勝ち抜けの形式です。
              </Box>
            </Card>
          </Link>
          <Link to="/config/nupdown">
            <Card>
              <Heading fontSize="xl">N updown</Heading>
              <Box>
                N回正解で勝ち抜けですが、途中で一度でも誤答すると0に戻る形式です。
              </Box>
            </Card>
          </Link>
          <Link to="/config/swedishx">
            <Card>
              <Heading fontSize="xl">Swedish X</Heading>
              <Box>1回の正答で+1,n回目の誤答で-nでXを目指す形式です。</Box>
            </Card>
          </Link>
          <Link to="/config/attacksurvival">
            <Card>
              <Heading fontSize="xl">Attack Survival</Heading>
              <Box></Box>
            </Card>
          </Link>
          <Link to="/config/Squarex">
            <Card>
              <Heading fontSize="xl">Square X</Heading>
              <Box>
                奇数問目と偶数問目の正解数をかけた数がX以上になれば勝ち抜けの形式です。
              </Box>
            </Card>
          </Link>
        </Grid>
      </Box>
    </Flex>
  );
};

export default Home;

// src/views/Home.vue
<template>
  <div class="home">
    <div class="content">
      <p>Ver.0.9.0</p>
      <p>
        最新のバージョンは<a
          href="https://github.com/newt-20st/score-watcher/releases"
          target="_blank"
          >こちらのリポジトリ</a
        >から確認してください。
      </p>
      <h2>形式を選択</h2>
      <div class="formatList">
        <router-link to="/config?type=json">
          <h3>設定ファイルから読み込む</h3>
          <div>
            過去に設定した際に出力したファイルから形式データを読み込みます。
          </div>
        </router-link>
        <router-link to="/config?type=count"
          ><h3>スコア計算</h3>
          <div>単純にスコアを計算します。</div></router-link
        >
        <router-link to="/config?type=nomx">
          <h3>N o M x</h3>
          <div>N回正解で勝ち抜け、M回誤答で失格の形式です。</div></router-link
        >
        <router-link to="/config?type=nbyn">
          <h3>N by N</h3>
          <div>
            正答数と誤答数2つの変数を持ち、それぞれの初期値は0とNです。2つの変数の積がN
            ** 2に達したら勝ち抜けの形式です。
          </div></router-link
        >
        <router-link to="/config?type=nupdown">
          <h3>N updown</h3>
          <div>
            N回正解で勝ち抜けですが、途中で一度でも誤答すると0に戻る形式です。
          </div></router-link
        >
        <router-link to="/config?type=SwedishX">
          <h3>Swedish X</h3>
          <div>
            1回の正答で+1,n回目の誤答で-nでXを目指す形式です。
          </div></router-link
        >
        <router-link to="/config?type=AttackSurvival">
          <h3>Attack Survival</h3>
          <div></div
        ></router-link>
        <router-link to="/config?type=SquareX">
          <h3>Square X</h3>
          <div>
            奇数問目と偶数問目の正解数をかけた数がX以上になれば勝ち抜けの形式です。
          </div></router-link
        >
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Home",
};
</script>
<style lang="scss" scoped>
.home {
  margin: 1rem;
  border-top: 3px solid $base-color;
}
.formatList {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1vw;
  margin: 1vw 0;
  a {
    display: block;
    background-color: $back-color;
    color: $base-color;
    text-decoration: none;
    border: 0.3rem solid $base-color;
    border-radius: 2rem;
    padding: 1rem;
    height: 25vh;
    transition: all ease-in 0.3s;
    overflow-y: hidden;
    h3 {
      font-size: 1.5rem;
      font-weight: 800;
      line-height: 1.5rem;
    }
    div {
      font-size: 1rem;
      line-height: 1rem;
    }
    &.wait {
      color: gray;
      border: 0.3rem solid gray;
      &:hover {
        background-color: gray;
        color: $back-color;
      }
    }
    &:hover {
      background-color: $base-color;
      color: $back-color;
    }
    &:first-child {
      color: $correct-color;
      border: 0.3rem solid $correct-color;
      &:hover {
        background-color: $correct-color;
        color: $back-color;
      }
    }
  }
}
</style>
